### ISSUE TITLE
The game does not fit my screen size.

### ISSUE THREAD

**Issue by Jonas-Salcedo** [JoshuaCrotts/SDL-Brick-Breaker#1]
I am running this game on a Lenovo YOGA 730-131KB and whenever I run this game, much of the screen is cropped off. What is the resolution of the computer you used to run the game? How can I fix this? My display has a resolution of 1960x1080.

**Comment by joshuacrotts** [comment]
That's interesting. The game is run at 590x960 resolution. Can you post a screenshot of the bug? If you want to change the resolution yourself, go into lib/stds/include/stddefine.h and change SCREEN_WIDTH and SCREEN_HEIGHT respectively.

**Comment by Jonas-Salcedo** [comment]
![Screenshot (188)](https://user-images.githubusercontent.com/8290414/86536261-c0b51780-beab-11ea-878b-fb4a2f6fc899.png)

**Comment by Jonas-Salcedo** [comment]
I also tried changing the resolution. The ball ended up going straight through the bricks without the ball so much as touching the paddle.
![Screenshot (200)](https://user-images.githubusercontent.com/8290414/86536334-4f299900-beac-11ea-980f-876f95e0f5cb.png)
![Screenshot (201)](https://user-images.githubusercontent.com/8290414/86536335-505ac600-beac-11ea-860c-b1602c996c42.png)
![Screenshot (202)](https://user-images.githubusercontent.com/8290414/86536336-505ac600-beac-11ea-8ced-519153f19fd5.png)
![Screenshot (203)](https://user-images.githubusercontent.com/8290414/86536337-50f35c80-beac-11ea-802b-a5eee25e70b1.png)
![Screenshot (204)](https://user-images.githubusercontent.com/8290414/86536338-518bf300-beac-11ea-9c64-f968be9a6ebf.png)
![Screenshot (205)](https://user-images.githubusercontent.com/8290414/86536339-518bf300-beac-11ea-96ec-786f686287c2.png)

**Comment by fudgenuggets12** [comment]
![Screenshot (199)](https://user-images.githubusercontent.com/8290414/86536347-5f417880-beac-11ea-8665-93a102320e61.png)

**Comment by joshuacrotts** [comment]
The ball is designed to spawn at a specific coordinate upon starting the level, and with your resolution, it's probably above the lowest layer of bricks. You can either edit the level text file to remove the last row of bricks, or change the spawn position of the ball. Try that and see what it does.

**Comment by Jonas-Salcedo** [comment]
I fixed the issue. My resolution was at 150%. I changed it to 100% and it worked fine.

**Comment by joshuacrotts** [comment]
Great! If you have any other suggestions, bug-fixes or features you want to add, feel free to make a pull request!

**Comment by midzer** [comment]
Hi,

my laptop screen size is 1280x800, so current window height of 960px is too big.

When I change to

```
#define S_WIDTH 295
#define S_HEIGHT 480
```

in `main.c` scaling is off:
![2024-09-15_14-47](https://github.com/user-attachments/assets/48801239-37a4-4a13-a595-0d0052c020ae)
